# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pairwise_prod <- function(x) {
    .Call('_kdca_pairwise_prod', PACKAGE = 'kdca', x)
}

.dkat_statistic <- function(Ux, dx, Uy, dy) {
    .Call('_kdca_dkat_statistic', PACKAGE = 'kdca', Ux, dx, Uy, dy)
}

.dkat_speed_cpp <- function(Ux, dx, Uy, dy) {
    .Call('_kdca_dkat', PACKAGE = 'kdca', Ux, dx, Uy, dy)
}

.quick_lm_boot_cpp <- function(Xs, Ys) {
    .Call('_kdca_quick_lm_boot_cpp', PACKAGE = 'kdca', Xs, Ys)
}

.quick_svd <- function(X) {
    .Call('_kdca_quick_svd', PACKAGE = 'kdca', X)
}

